[package]
name = "rhit"
version = "1.5.1-dev"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/rhit"
description = "nginx log analyzer"
edition = "2018"
keywords = ["log", "nginx", "analyzer"]
license = "MIT"
categories = []

[dependencies]
anyhow = "1.0"
argh = "0.1.3"
bet = "0.4.0"
crossterm = "0.19.0"
cli-log = "1.2"
file-size = "1.0.3"
flate2 = "1.0"
have = "0.1.1"
itertools = "0.10"
lazy-regex = "0.1.3"
lazy_static = "1.4"
log = "0.4"
minimad = "0.7.0"
num-format = "0.4"
regex = "1.4"
smallvec = "1.6"
termimad = { version = "0.10.0", default-features = false, features = ["special-renders"] }
thiserror = "1.0"


[profile.release]
debug = false
lto = "fat"
codegen-units = 1

[patch.crates-io]
# bet = { path = "../bet" }
# have = { path = "../have" }
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
# cli-log = { path = "../cli-log" }
