[package]
name = "rhit"
version = "0.1.0"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/rhit"
description = "my personal nginx log analyzer"
edition = "2018"
keywords = ["log", "nginx", "analyzer"]
license = "MIT"
categories = []


[dependencies]
anyhow = "1.0"
argh = "0.1.3"
chrono = "0.4"
crossterm = "0.17.7"
cli-log = "0.1"
file-size = "1.0.3"
have = "0.1.1"
itertools = "0.10"
lazy_static = "1.4"
log = "0.4"
minimad = "0.6.7"
regex = "1.4"
termimad = "0.9.2"
thiserror = "1.0"

[patch.crates-io]
#have = { path = "../have" }
minimad = { path = "../minimad" }
termimad = { path = "../termimad" }
