[package]
name = "rhit"
version = "0.1.0"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/rhit"
description = "my personal nginx log analyzer"
edition = "2018"
keywords = ["log", "nginx", "analyzer"]
license = "MIT"
categories = []


[dependencies]
