[package]
name = "rhit"
version = "1.0.5"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/rhit"
description = "nginx log analyzer"
edition = "2018"
keywords = ["log", "nginx", "analyzer"]
license = "MIT"
categories = []

[dependencies]
anyhow = "1.0"
argh = "0.1.3"
bet = "0.4.0"
crossterm = "0.17.7"
cli-log = "0.1"
file-size = "1.0.3"
flate2 = "1.0"
have = "0.1.1"
itertools = "0.10"
lazy_static = "1.4"
log = "0.4"
minimad = "0.6.9"
regex = "1.4"
termimad = "0.9.5"
thiserror = "1.0"

[profile.release]
debug = false
lto = true
codegen-units = 1

[patch.crates-io]
# bet = { path = "../bet" }
# have = { path = "../have" }
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
